spring:
  hikari:
    pool-name: HikariCP
    maximum-pool-size: 250
    auto-commit: true
    idle-timeout: 6000
    max-lifetime: 180000
    connection-timeout: 3000
    connection-test-query: SELECT 1
    validation-timeout: 5000

## 多数据源配置
datasources:
  driver: com.mysql.cj.jdbc.Driver
  hl:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://omo.testmdb.xdf.cn:3306/hl_live?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=GMT%2b8
      username: root
      password: JORhplEHRsA7imKe
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://omo.testsdb.xdf.cn:3306/hl_live?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=GMT%2b8
      username: root
      password: JORhplEHRsA7imKe
  tb:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://omo.testmdb.xdf.cn:3306/teachingbox?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=GMT%2b8
      username: root
      password: JORhplEHRsA7imKe
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://omo.testsdb.xdf.cn:3306/teachingbox?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&serverTimezone=GMT%2b8
      username: root
      password: JORhplEHRsA7imKe