spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.97.235:3306/gre_test_library?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:templates/
server:
  port: 8080


com:
  fb:
    app:
      id: 323618148252567
      secret: 8fb1deef6797bdb6ffe4f9e045dd7545
